### ISSUE TITLE
Schemas are not returned in the APIs right after editing the database connection details

### ISSUE THREAD

**Issue by rajatvijay** [mathesar-foundation/mathesar#3230] opened 2023-10-03 16:15 UTC
## To Reproduce

1. Add a new database connection from the mathesar UI.
3. Rename the database from the postgres server. 
4. Reload the database page of this particular database on mathesar.
5. Expect connection error on the page.
6. Click on the "Edit Connection" button. 
7. Change the name & click on the "Update the connection" button. 
8. Get redirected to the database page of this particular database. 
9. Expect to see the schemas from this database. Instead see no schemas being listed. 

## Additional information

1. Frontend calls the `POST: /api/ui/v0/reflect/` API right the editing of the database connection succeeds. 
2. To reproduce this please use the branch: `db-connection-pages`

**Comment by dmos62** [comment] 2023-10-03 17:09
Still can't reproduce. Could be some kind of race condition, but the `/api/ui/v0/reflect/` seems to be blocking.

I'll start out by having backend automatically reflect when you edit a connection string. And, to only reflect the affected db (the `/reflect` endpoint reflects everything).

**Comment by Anish9901** [comment] 2023-10-04 13:54
> I'll start out by having backend automatically reflect when you edit a connection string. And, to only reflect the affected db (the /reflect endpoint reflects everything).

@dmos62 I already tried to do that, but it results in a bunch of failed test cases.

**Comment by dmos62** [comment] 2023-10-05 09:58
@Anish9901 yeah, I'm running into some tech debt. You'd want to reflect the database whenever you make changes to the connection string (because it might now be a totally different database), but during reflection we actually make changes to the database models too (to mark them as deleted or not deleted), which causes infinite recursion. I think it's fairly important to get reflection right; I'm seeing what I can do.

**Comment by Anish9901** [comment] 2023-10-05 11:59
One possible solution I see for this problem is to detect which fields are altered in the model and triggering reflection only when `db_name`, `name`, `host` or `port` are changed, but that might not be a quick fix given the urgent priority of this issue.

**Comment by dmos62** [comment] 2023-10-23 20:53
> One possible solution I see for this problem is to detect which fields are altered in the model and triggering reflection only when `db_name`, `name`, `host` or `port` are changed, but that might not be a quick fix given the urgent priority of this issue.

I had similar ideas. Though I opted to just get rid of the `deleted` field altogether. Seemed like a confused concept, and it wasn't used by frontend. And, there was a whole bunch of other buggy weirdness associated with it. Now, we just do a connectability check whenever listing databases in the API, and we don't persist the result of that. If it turns out that we want to persist it for some reason (right now we don't need to), we can come up with something better than `deleted`.

**Comment by dmos62** [comment] 2023-10-24 01:35
When rebasing #3223 on top of #3245, I can't reproduce this anymore. Though, before I wasn't able to reproduce too, sort of: then I succeeded to reproduce, and couldn't tell why I couldn't reproduce from the beginning. My point is that I'm not confident that the bug is fixed.

@rajatvijay would you find the time to checkout #3223, merge #3245 on top (note that it removes the `deleted` field from `AppTypes.ts`), and see if you can reproduce? Even if #3223 is dead, we need to fix this bug. If you succeed in reproducing, could you check if the steps you follow are exactly as described in the top post?

**Comment by rajatvijay** [comment] 2023-10-24 05:30
Sure @dmos62 I will get to it later today or first thing in morning tomorrow.

**Comment by dmos62** [comment] 2023-10-24 14:15
@rajatvijay thanks! By the way, with changes in that pr, frontend shouldn't have to trigger reflection manually when making changes via api.

**Comment by seancolsen** [comment] 2023-11-01 16:55
@mathemancer since you're already assigned to the corresponding [PR](https://github.com/centerofci/mathesar/pull/3245), I'm assigning you to figure out the next steps with this issue no that Dom will non longer be working on it.

**Comment by mathemancer** [comment] 2023-12-22 08:16
@seancolsen This seems to be difficult to reproduce. I'm going to try to reproduce it myself, and close this if I can't. We can reopen or create a fresh issue.

**Comment by mathemancer** [comment] 2023-12-22 08:41
Okay, I tried a few times and can't reproduce. I did crash into the bug reported in #3329 , and we should certainly resolve that one.

**Closed by mathemancer** 2023-12-22 08:41 UTC
Labels: type: bug, affects: ux, work: backend, status: draft, restricted: maintainers, priority: urgent
