### ISSUE TITLE
In Safari, selecting cells also selects their contents

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#2806] opened 2023-04-11 15:00 UTC
## Chrome/Firefox (good)

https://user-images.githubusercontent.com/42411/231203515-8316377c-c4fe-49a3-a638-ed9931df37da.mp4

## Safari (bad)

https://user-images.githubusercontent.com/42411/231202937-ac872825-a64e-4316-82d9-51b14fae1da0.mp4

## Notes

- This is a regression. I'd like to look at #2792 to see if it was introduced there.
- This was originally reported by @pavish [here](https://github.com/centerofci/mathesar/pull/2773#pullrequestreview-1379350606)

**Comment by seancolsen** [comment] 2023-04-11 15:40
@rajatvijay would you be interested in taking this up? I think we ought to try hard to get this in the next release.

Interestingly, I had a need last week to disable user selection under similar circumstances, and I handled it via JS [like this](https://github.com/centerofci/mathesar/pull/2808/files#diff-35024507b4bfe84f744d560bdbc270b52e07c3d8d290d4ec7e4fdffc279280a5R127)

1. When the user begins dragging, I do:

    ```ts
    window.addEventListener('selectstart', disableSelect, true);
    ```

1. That calls `disableSelect`, which is:

    ```ts
    function disableSelect(event: Event) {
      event.preventDefault();
    }
    ```

1. Then when the user stops dragging, I do:

    ```ts
    window.removeEventListener('selectstart', disableSelect, true);
    ```

This seems to work well, including in Safari. Maybe we could adopt that approach for the cell selection too?

**Comment by rajatvijay** [comment] 2023-04-11 15:47
@seancolsen sure. I'll take this up.

**Comment by pavish** [comment] 2023-04-18 18:11
@rajatvijay @seancolsen This issue is high priority since it's a regression and it also affects the copy feature on Safari implemented in https://github.com/centerofci/mathesar/pull/2773.

Since we would have https://github.com/centerofci/mathesar/pull/2773 for 0.1.2 as it is merged, it would be best if we can have this for 0.1.2 as well.

**Comment by rajatvijay** [comment] 2023-04-19 10:28
@pavish you are right, will have the PR by the end of this week

**Closed as completed** 2023-04-24 21:39 UTC
Labels: work: frontend, ready, regression
