### ISSUE TITLE
Fix hint system so that it doesn't have to be stubbed

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#1983] opened 2022-11-25 12:54 UTC
We're currently hardcoding on the frontend what filters, preproc functions are available and/or how they can be used. We designed the hint system for that, but there was some problem with that, so we ended up hardcoding, and postponed fixing the actual problem.

I don't recall what the actual problem was. @pavish do you have insights?

**Comment by pavish** [comment] 2023-03-15 16:33
@dmos62 The hint system we have is too general for the frontend to make use of. The parsing and restructuring the response requires the frontend to be aware of all the hints, and hardcoding the stub was much easier since the frontend had to know about the hints anyway.

This can be discussed further when the issue is picked up.

**Comment by Anish9901** [comment] 2024-01-15 18:27
@pavish I'm closing this since it seems irrelevant. Please reopen it if you feel otherwise.

**Closed by Anish9901** 2024-01-15 18:27 UTC
Labels: type: enhancement, affects: dx, affects: architecture, affects: technical debt, work: backend, status: draft
