### ISSUE TITLE
Temporary `DataFile` object is not deleted once the Table has been created

### ISSUE THREAD

**Issue by IamEzio** [mathesar-foundation/mathesar#2910] opened 2023-06-03 12:26 UTC
## Description

When we import data to a table from a file, we store the file temporarily as a `DataFile` object. When we complete the import process and a Table has been created, this DataFile instance is not deleted resulting in data redundancy.

https://github.com/centerofci/mathesar/assets/89375125/8f1190c6-8722-4c4d-991d-ae7e5ba8cd93

## Expected behavior

The temporary `DataFile` instance should be deleted once the Table has been created.

### To import a file
1. Click on `New Table` > `From Data Import`.
2. Select a `csv` file. (Or any other supported file format).
3. Click `Confirm & Create Table`.

### To use Python shell as shown in the video above
1. Run the command: 
```
docker exec -it mathesar_service_dev python manage.py shell
```
2. Run the following lines in python shell:
```
from mathesar.models.base import DataFile
print(DataFile.objects.count())
```

## Environment
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Browser Version: Version 104.0.5112.79

**Comment by dmos62** [comment] 2023-06-05 10:41
@silentninja are you aware of any reason to keep `DataFile`s around after an import has finished?

**Comment by silentninja** [comment] 2023-06-05 19:46
We store the `DataFile` when importing it into an existing `Table`.

**Comment by dmos62** [comment] 2023-06-06 14:02
@kgodey @silentninja thanks for the context. So it makes sense to get rid of `DataFile` when import is finished, keeping in mind that edge case @silentninja [mentioned](https://github.com/centerofci/mathesar/issues/2910#issuecomment-1577376382).

**Comment by dmos62** [comment] 2023-07-17 11:05
@Anish9901 @IamEzio I see you guys [have been discussing this](https://github.com/centerofci/mathesar/issues/3028#issuecomment-1635885578). I'd just like to add that this seems like an unimportant optimization at the moment, because there have been no reported problems caused by this and the hypothetical UX problems seem pretty difficult to cause. Let me know if I'm missing anything though.

**Comment by Anish9901** [comment] 2023-07-17 11:16
Yes, @dmos62 I just wasn't aware about what happened about this since we talked about it last time, to which I got to know that it wasn't a high enough priority right now, that's all we discussed about this.

**Comment by Anish9901** [comment] 2023-07-17 11:46
That makes sense @dmos62 I just wasn't aware of the reason these files were stored in the first place that's why I decided to document it in the meeting notes as a todo.

**Comment by seancolsen** [comment] 2023-12-05 19:29
We discussed this during today's product approval meeting. Notes:

- Kriti and Brent had medium-strong opinions that we should _keep_ the data file because it may be useful. However they acknowledged that Mathesar currently provides no way to actually use it, so they are open to deleting the data file.
- Pavish initially felt strongly that we delete the data file, but the acknowledged that is is a very low priority issue.
- Anish also expressed support for deleting it.
- In the end everyone was sick of debating it, so we decided to close the issue. We can take this up later if it becomes a problem.

Given that Mathesar provides no way to use the data file, we would be okay with deleting the data file. But it's not a task that we want to spend time tracking right now.

Ideally we'd add additional features, giving users the capability to manage the data file manually, potentially making use of it or cleaning it up. But again, that work is not a priority right now and not likely to become a priority any time soon.

**Closed by seancolsen** 2023-12-05 19:29 UTC
Labels: type: bug, affects: technical debt, work: backend, status: draft
