### ISSUE TITLE
Active/Focused Cell is displayed over the Row Number Cell

### ISSUE THREAD

**Issue by catfo435** [mathesar-foundation/mathesar#3380] opened 2024-01-03 16:05 UTC
### Unexpected Cell UI Behavior

Once you scroll enough that an active/focused cell overlaps with the row number cell at the left of the page, the active/focused cell is displayed over the Row Number cell as you continue scrolling right.

## Expected behavior

The Row number cell should be displayed above the active/focused cell.

## To Reproduce
- Zoom up to 200% or add enough columns for the horizontal scrollbar to appear.
- Select any cell.
- Scroll left until the cell reaches extreme left.
- Find it being displayed above the Row Number cell.

## Environment
Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0

## Screenshots
![image](https://github.com/mathesar-foundation/mathesar/assets/74195851/ddf22a1e-c540-4c5d-b7d5-d3f4a0d587c8)

## Proposed Solution

Change the z-index in Sheet.svelte
```
--z-index__sheet__top-left-cell: 5;
```
![image](https://github.com/mathesar-foundation/mathesar/assets/74195851/77d666dc-e93d-4e7b-9353-8747b5cb9f5e)

**Comment by seancolsen** [comment] 2024-01-03 16:57
Thanks for reporting this, @catfo435. I've assigned it to you since you [expressed](https://matrix.to/#/!vXLxAqmrJWsDMWPSpo:matrix.mathesar.org/$oJxPMBsqgIMje_9qYK_Rxq_P2wOVnFGWFeKirbar4yE?via=matrix.mathesar.org&via=matrix.org&via=t2bot.io) interest in working on it. Normally we don't assign issues to brand new contributors, but in this case I think it make sense since you reported it yourself.

**Comment by seancolsen** [comment] 2024-01-03 16:57
As far as your suggested change, I like the direction you're heading. I'll need to take a look at the code. Please tag me on your PR once you open it. Then I'll review it.

**Comment by aryan1306** [comment] 2024-01-09 12:05
Hi, can I contribute to this issue?

**Comment by seancolsen** [comment] 2024-01-09 13:14
@aryan1306 you're welcome to submit a PR for this issue, but note that this issue already has one [open PR](https://github.com/mathesar-foundation/mathesar/pull/3382). This means that there is a very small chance that any PR you open would actually be merged. For that reason I would suggest finding another issue to work on.

**Comment by seancolsen** [comment] 2024-02-01 14:07
Note: I was curious if this was a regression so I tested on Mathesar 0.1.3 and found the bug to be present there as well. I'm not certain when it began but I think we can safely say that is probably not a regression — at least, not one that occurred recently.

**Closed** 2024-02-01 16:41 UTC
Labels: type: bug, good first issue, help wanted, work: frontend, ready
