### ISSUE TITLE
Unable to load Preview of the table on importing data from csv file in demo mode

### ISSUE THREAD

**Issue by varshadr** [mathesar-foundation/mathesar#2793] opened 2023-04-07 16:01 UTC
## Description
 On creating a new table by importing the data from a csv file on Demo mode fails to load the preview of the table 

## Expected behavior
 On importing the csv file, the preview of the table must be displayed

## To Reproduce
  -Login to demo mode on Brave browser
- Create a new schema
- Create an new table from Data import
- Choose any csv file to import data
- It will fail to load the preview of the table 

## Environment
 - OS: ( macOS 11.5.1)
 - Browser: (Brave)
 - Browser Version: ( 1.29.77)
 - Other info:Works fine on chrome

## Additional context

[32C8586B-B033-4070-B228-C4959C4DE559](https://user-images.githubusercontent.com/114489823/230639000-b3d7dae6-17bb-430f-91ee-33c71dd8af20.jpeg)

**Comment by Aritra8438** [comment] 2023-04-07 16:34
This **network tab log** might be useful.

The ```GET``` request saying ```'NoneType' object has no attribute 'schema'```.

![image](https://user-images.githubusercontent.com/64671908/230644250-be037aaa-b5b0-4d96-9bf0-9868f221d66e.png)

**Comment by IamEzio** [comment] 2023-04-07 18:03
That is quite interesting, and I would like to investigate more. Could I be assigned to it?

**Comment by varshadr** [comment] 2023-04-07 18:14
Can I work on this issue?

**Comment by rajatvijay** [comment] 2023-04-12 10:51
Thanks for reporting @varshadr. This looks urgent hence I have put the label `restricted: maintainers` on it. 

@pavish: For now I have put this in the `Next Release` milestone but if we have the bandwidth we should prioritize this.

**Comment by kgodey** [comment] 2023-04-12 17:33
@IamEzio @varshadr feel free to investigate and post information about the root cause here if you have time. I suspect this is related to the demo server deployment, so I don't know if we can reproduce it locally, but more information won't hurt.

**Comment by IamEzio** [comment] 2023-04-12 19:00
@kgodey I am able to reproduce the error locally and am trying to find the cause behind it. The error traceback in server logs is not much helpful:
![Screenshot from 2023-04-13 00-10-08](https://user-images.githubusercontent.com/89375125/231554397-46b3d65e-58d5-42dc-94b2-1eec7402f7ec.png)

Since the request which is failing fetches information about the created datafile object, my initial thoughts were that the datafile object is not being created correctly. I used `print` statements at various places to check the same but it seems like it is working as expected. 
![Screenshot from 2023-04-13 00-21-17](https://user-images.githubusercontent.com/89375125/231556462-61f6866c-0f95-467f-8ba6-0895ccd65094.png)
The first print statement is used in `mathesar/utils/datafiles.py` where we create and save the datafile object. The second one is used in `create_table_from_csv` method in `mathesar/imports/csv.py` where we create a table from data file and update the datafile object. 


I am now trying to compare the workflow of creating tables from a data file in normal vs demo mode. The only difference I found is the usage of `LiveDemoModeMiddleware` when we run Mathesar in demo mode. I am trying to investigate if somehow it messes with creating datafile objects. Hopefully, I'll be able to get the answers soon.

**Comment by varshadr** [comment] 2023-04-13 18:18
> @IamEzio @varshadr feel free to investigate and post information about the root cause here if you have time. I suspect this is related to the demo server deployment, so I don't know if we can reproduce it locally, but more information won't hurt.

On it!

**Comment by dmos62** [comment] 2023-07-04 13:14
Reproduced. Here's a screenshot with the backend exception (`BadCopyFileFormat`): 
![Screenshot 2023-07-04 161419](https://github.com/centerofci/mathesar/assets/2715476/06398ea6-545d-4ac9-8d93-b3d5f07a0930)

**Comment by hitenvidhani** [comment] 2024-05-11 09:05
This is fixed as I am able to [load data](https://github.com/mathesar-foundation/mathesar/assets/60215053/18b087cc-3d15-4163-8496-da9861f91d53) using CSV in demo mode.

**Closed** 2024-05-13 12:28 UTC
Labels: type: bug, affects: ux, work: backend, ready, restricted: maintainers
