### ISSUE TITLE
Unable to delete an invalid connection

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3370] opened 2023-12-22 09:11 UTC
## Description
* Add a connection via any of the APIs. Eg., `/api/ui/v0/connections/create_from_scratch/`. Use invalid details for the host and port.
* Notice that the connection gets added since we do not test if it's valid while creating it.
* Now, attempt to delete this connection. It fails with a `500: Connection refused` error. This error is thrown despite `del_msar_schemas` being `false`. 
* This leads to never being able to remove a connection if the connection params are invalid or if the database is permanently down.

## Expected behavior
* Users should be able to delete connections without checking whether it's valid, when `del_msar_schemas` is `false`.

@mathemancer I'm marking this issue as `needs: backend approval` for you to review this.

**Comment by Anish9901** [comment] 2023-12-22 13:46
@pavish this issue is duplicate of #3361

**Closed** 2024-01-03 14:48 UTC
Labels: type: bug, work: backend, restricted: maintainers, needs: backend approval
