### ISSUE TITLE
Make it easy to install Mathesar when not using install.sh

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#2790] opened 2023-04-06 17:30 UTC
These steps make the build from source installation a little easier.
- [ ] Set up a GitHub action that automatically builds static files when we create a release
  - [ ] Update documentation to remove building static files manually.

**Comment by silentninja** [comment] 2023-04-06 17:30
Blocked by #2427

**Comment by kgodey** [comment] 2024-02-02 17:56
Closing, requirements out of date. Also seems like a duplicate of https://github.com/mathesar-foundation/mathesar/issues/3163

**Closed by kgodey** 2024-02-02 17:56 UTC
Labels: work: documentation, type: enhancement, needs: unblocking
