### ISSUE TITLE
Consistent error handling across the API

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#889] opened 2021-12-15 15:09 UTC
## Problem
We need a way to consistently handle exceptions and assign specific error codes based on the exception raised on per view basis 

## Proposed solution
Necessary components needed to handle the error spec:
1. Base components to assist with error handling and adhere exceptions to the API spec
2. The exception handler should support parsers to convert exceptions to a proper error response, so any exception that is not an `ApiException` such as errors thrown outside of the service layer can be converted into an error response that conforms to the API standards #1016 Adds this feature
3. Parsers that should be able to accept an exception and convert the exception into a proper error response and assign a error code and return it. #991 adds this feature
4. The custom error code should be a `view` layer responsibility. It should be declared by the view layer so that exceptions can be reused and the custom codes can vary based on the `API route`. #991 adds this feature
5. Categorize errors more specifically instead of throwing broad exception. This should be handled on an ad-hoc basis, maybe a comment thread or separate issue listing errors that don't have a distinguishable exception. 

## Component Issues 
- [x] #623: should be able to handle requirements 1 and 2 above
- [x] #883: should be able to handle requirements 3 and 4. We could take some ideas for [drf-friendly-errors](https://github.com/FutureMind/drf-friendly-errors)
- [x] #859
- [x] #983
- [x] #1021
- [x] #1023 
- [x] #1030

**Comment by silentninja** [comment] 2021-12-15 15:22
@dmos62 @mathemancer @kgodey Let me know if this list makes sense

**Comment by kgodey** [comment] 2021-12-16 02:38
Looks fine to me.

**Comment by dmos62** [comment] 2021-12-16 10:08
> custom codes can vary based on the API route

Do we want error codes to vary based on API route? Say you're passing a filter or grouping specification and its parsing fails. It doesn't really matter which endpoint you're using, the problem is with the filter spec/parser. There might be cases where we want error codes to vary based on API route, but I can't think of one at the moment.

**Comment by silentninja** [comment] 2021-12-16 13:42
@dmos62 The filters should throw custom exceptions, which shows that the problem is with the filter spec. But custom code is more of an API requirement and the exceptions shouldn't have to be concerned about it. We cannot expect exceptions outside the service layer to know about the API requirement.

**Comment by mathemancer** [comment] 2021-12-17 08:23
@silentninja This makes sense to me.

**Comment by kgodey** [comment] 2024-02-02 17:51
Closing, all sub-issues are done.

**Closed by kgodey** 2024-02-02 17:51 UTC
Labels: affects: architecture, work: backend, type: meta, pr-status: revision
