### ISSUE TITLE
Active cell is reset to its initial position after column property changes are made

### ISSUE THREAD

**Issue by FidalMathew** [mathesar-foundation/mathesar#3221] opened 2023-09-21 11:02 UTC
## Expected behavior
If a user changes the column property such as "Restrict to Unique" or "Disallow NULL Values", the active cell should remain the same. 

## To Reproduce
Select a cell in a column. Now, in the sidebar, select the option "Column" and under the "Properties" section, select the option "Restrict to Unique" or "Disallow NULL Values". After effects are made, the first cell of the table will become the active cell.

## Environment
 - OS: Windows
 - Browser: Chrome

## Additional context

Before:

![image](https://github.com/centerofci/mathesar/assets/84982038/4d9eeb53-efaf-4afa-bcb7-7adf8f152a3c)

After: (selecting "Disallow NULL Values" option)

![image](https://github.com/centerofci/mathesar/assets/84982038/eab0b876-7ff8-4294-98d0-682a2923689e)

## Status

Blocked on larger refactoring that needs to happen within the front end.

**Comment by FidalMathew** [comment] 2023-09-21 11:03
I would like to work on this issue :). Kindly assign me.

**Comment by FidalMathew** [comment] 2023-09-23 05:26
@seancolsen sure! Thanks for letting me know 😊

**Comment by Vaidik-patil** [comment] 2023-10-13 14:30
i am interested to work on it

**Comment by seancolsen** [comment] 2023-10-13 14:43
No @Vaidik-patil this one is restricted to maintainers only due to the amount of refactoring it will entail.

**Comment by seancolsen** [comment] 2024-03-04 10:24
This is still blocked.

**Comment by seancolsen** [comment] 2024-11-06 16:23
I'm no longer able to reproduce this, so I'm closing.

**Closed by seancolsen** 2024-11-06 16:23 UTC
Labels: type: bug, work: frontend, needs: unblocking, restricted: maintainers
