### ISSUE TITLE
Convert empty strings to NULL when saving values in temporal columns

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#2073] opened 2022-12-12 11:43 UTC
## Description
In our Cycle 6 worksheet in staging, the Due Date column is a date column that does not have "Disallow NULL values" ticked. If I try to reset a Due Date cell to `NULL`, I can't: a popup (if that's the correct term) is shown saying `Unable to save cell. Invalid date format`.

## Expected behavior
I want to be able to reset any cell to `NULL`, including date cells (as long as its column is not NULL-constrained).

**Comment by seancolsen** [comment] 2022-12-12 14:12
@dmos62 I'm not able to reproduce this. Here's my attempt:

![Peek 2022-12-12 09-11](https://user-images.githubusercontent.com/42411/207066969-28255d42-6476-44dd-84f4-d41e51226741.gif)

Would you be able to upload a screencap which demonstrates the reproduction steps you're taking?

**Comment by dmos62** [comment] 2022-12-12 15:41
@seancolsen oh, I didn't realise we had a right-click menu: that does work.

What I do for resetting cells to `NULL` is double-click them to enter editing mode, and then I delete every character in the cell. It works for the percentages column, for example. I think this should work for other cells as well.

**Comment by pavish** [comment] 2022-12-12 16:34
@seancolsen

> do you see any concern with inferring NULL values from empty string on the temporal column types

I don't see any concern.

**Comment by kgodey** [comment] 2024-02-02 18:03
Closing this, this doesn't seem like a priority / worth the effort, not sure what problem it solves.

**Closed by kgodey** 2024-02-02 18:03 UTC
Labels: type: bug, affects: ux, work: frontend, ready
